### ISSUE TITLE
Whitelist Contract

### ISSUE THREAD

**Issue by yuriy77k** [jointerinc/jointer-token#10]
There are some issues:
1. In function `getNextConstant()` you check [nextConstant](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L299) to be less then MAX uint32,  This means that you can use on 32 bits from `nextConstant` instead of 64.
Better to replace is with  `require(counter < 64)` just after [counter++](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L296).

2. `flags` and `associatedConstant` have type `uint64` but [constants](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L23-L39) have types `uint8` and `uint16`. It have to be `uint64` too (to avoid compiler warnings).

3. Smart Swap is forever and always allowed. [This bit](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L36) is not necessary. 

4. According this [condition](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L369-L373) if address `_to` is not in the `isAllowedAddressConstant` the transfer to this address allowed. To restrict some address of receiving token is require to add this address to the 'isAllowedAddressConstant' with a bits that should be checked. Right? 
How we can restrict users from USA to transfer token to users from China, for example?

5. What is [investorType](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L12) and [here](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L43)?

**Comment by yashnaman** [comment]
> In function getNextConstant() you check nextConstant to be less then MAX uint32, This means that you can use on 32 bits from nextConstant instead of 64.
Better to replace is with require(counter < 64) just after counter++.

1.Yes. It was an oversight from my side. It will be fixed in the next commit.

> flags and associatedConstant have type uint64 but constants have types uint8 and uint16. It have to be uint64 too (to avoid compiler warnings).

2. I thought it was not a [problem](https://solidity.readthedocs.io/en/v0.5.3/types.html#implicit-conversions).  Happy to discuss more.


> Smart Swap is forever and always allowed. This bit is not necessary.
3. We can remove it. No problem.

> According this condition if address _to is not in the isAllowedAddressConstant the transfer to this address allowed. To restrict some address of receiving token is require to add this address to the 'isAllowedAddressConstant' with a bits that should be checked. Right?
How we can restrict users from USA to transfer token to users from China, for example?

4. We were thinking of using [InvestorType](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L12) for. A person from the USA can be of x InvestorType(i.e. 6) which is not allowed to a person from china which of InvestorType y(i.e. 7). [Here](https://github.com/jointerinc/jointer-token/blob/3f1d51d92a5e3a49e0e715320da0f98e99d9e534/contracts/WhiteList/WhiteList.sol#L384). I guess this answers 5th too. Doing this with only flags was proving to be inefficient.

**Comment by yashnaman** [comment]
Also, Can you give us an example in the form of .csv maybe with a bunch of addresses and where they are from and what type they are? Are they allowed with each other or not. It would be helpful.

Address/ Country/ Type(Accredited, Qualified,Retail)  => Allowed addresses of  with which Countries and what type

Which types are always allowed to trade with what types?
[Table1](https://gist.github.com/yuriy77k/62a65dee304bd3dbeab0fea52ea0c8d5#whitelist-structure) was helpful but if you could provide this then it would be great.

**Comment by yuriy77k** [comment]
## Whitelist contract has two parts:
1. Whitelist - is a layer which allow or disallow user to **Receive** token. Should be three external functions (one for each token): `main_AllowedReceive(address user) external returns (bool)`, `etn_AllowedReceive(address user) external returns (bool)`, `stock_AllowedReceive(address user) external returns (bool)`.
2. Authorization layer - allow or disallow to **Transfer** token. It checks both sender and receiver of token and represented with three external functions (one for each token): `main_AllowedTransfer(address _from, address _to) external returns (bool)`, `etn_AllowedTransfer(address _from, address _to) external returns (bool)`, `stock_AllowedTransfer(address _from, address _to) external returns (bool)`.

## Investor (user)
Investor represented by two mappings:
``` solidity
    struct UserDetails {
        uint256 flags;	// bitmap, where each bit correspondent to some properties (additional flags can be added in future).
        uint256 maxWallets;
    }

    mapping(address => address) public address_belongs;
    mapping(address => UserDetails) public user_details;
```

**Flags** are like the investor's properties, that indicate what a type of investor (i.e. Passed the KYC, from USA, belong Binance, is Accredited, etc.). It is a combination of different types.

**Comment by yashnaman** [comment]
Am I right to put these in the flag of every whiteListed Address?

- [ ] IsHoldBackDaysOverMain
- [ ] IsHoldBackDaysOverEtn
- [ ] IsHoldBackDaysOverStock
- [ ] IsTokenMatureMain
- [ ] IsTokenMatureEtn
- [ ] IsTokenMatureStock

We will set these bits for every address and put the rule in receiving rules. Once the period is over we will update the mask in receiving rule so that it won't matter what these bits are set to.
